apiVersion: v1
kind: Service
metadata:
  labels:
    app: jbpm
  name: jbpm
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: jbpm
  type: LoadBalancer
